name: Render diagrams

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Render PlantUML diagrams
        run: |
          mkdir -p docs/diagrams
          docker run --rm -v "$PWD":/workspace -w /workspace plantuml/plantuml -tpng docs/architecture-component.puml -o docs/diagrams
          docker run --rm -v "$PWD":/workspace -w /workspace plantuml/plantuml -tsvg docs/architecture-sequence.puml -o docs/diagrams

      - name: Commit rendered diagrams
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/diagrams || true
          git commit -m "chore(diagrams): render PlantUML diagrams" || echo "no changes to commit"
          git push || echo "push failed"
